version: "3.9"
services:
  api:
    build: ./backend
    environment:
      - DATABASE_URL=file:./dev.db
      - PORT=4000
      - ADMIN_TOKEN=${ADMIN_TOKEN:-change-me-super-secret}
    ports:
      - "4000:4000"
    volumes:
      - ./backend/prisma:/app/prisma
      - ./backend/src:/app/src
    command: sh -c "npx prisma generate && npx prisma migrate deploy && node src/server.js"

  web:
    build: ./frontend
    environment:
      - VITE_API_URL=http://localhost:4000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: sh -c "npm run dev -- --host"